package Model;
// Generated May 9, 2016 4:38:09 PM by Hibernate Tools 4.3.1



/**
 * Doctor generated by hbm2java
 */
public class Doctor  implements java.io.Serializable {


     private String userId;
     private User user;
     private String phone;
     private String email;

    public Doctor() {
    }

    public Doctor(User user, String phone, String email) {
       this.user = user;
       this.phone = phone;
       this.email = email;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

}


