package Model;
// Generated 18/05/2016 08:50:39 PM by Hibernate Tools 4.3.1



/**
 * PatientappointmentsId generated by hbm2java
 */
public class PatientappointmentsId  implements java.io.Serializable {


     private int patientAppointmentsId;
     private String patientRecordId;

    public PatientappointmentsId() {
    }

    public PatientappointmentsId(int patientAppointmentsId, String patientRecordId) {
       this.patientAppointmentsId = patientAppointmentsId;
       this.patientRecordId = patientRecordId;
    }
   
    public int getPatientAppointmentsId() {
        return this.patientAppointmentsId;
    }
    
    public void setPatientAppointmentsId(int patientAppointmentsId) {
        this.patientAppointmentsId = patientAppointmentsId;
    }
    public String getPatientRecordId() {
        return this.patientRecordId;
    }
    
    public void setPatientRecordId(String patientRecordId) {
        this.patientRecordId = patientRecordId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PatientappointmentsId) ) return false;
		 PatientappointmentsId castOther = ( PatientappointmentsId ) other; 
         
		 return (this.getPatientAppointmentsId()==castOther.getPatientAppointmentsId())
 && ( (this.getPatientRecordId()==castOther.getPatientRecordId()) || ( this.getPatientRecordId()!=null && castOther.getPatientRecordId()!=null && this.getPatientRecordId().equals(castOther.getPatientRecordId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPatientAppointmentsId();
         result = 37 * result + ( getPatientRecordId() == null ? 0 : this.getPatientRecordId().hashCode() );
         return result;
   }   


}


