package Model;
// Generated 18/05/2016 08:50:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Patientrecord generated by hbm2java
 */
public class Patientrecord  implements java.io.Serializable {


     private String patientRecordId;
     private Patient patient;
     private Set patientappointmentses = new HashSet(0);

    public Patientrecord() {
    }

	
    public Patientrecord(Patient patient) {
        this.patient = patient;
    }
    public Patientrecord(Patient patient, Set patientappointmentses) {
       this.patient = patient;
       this.patientappointmentses = patientappointmentses;
    }
   
    public String getPatientRecordId() {
        return this.patientRecordId;
    }
    
    public void setPatientRecordId(String patientRecordId) {
        this.patientRecordId = patientRecordId;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public Set getPatientappointmentses() {
        return this.patientappointmentses;
    }
    
    public void setPatientappointmentses(Set patientappointmentses) {
        this.patientappointmentses = patientappointmentses;
    }




}


