package Model;
// Generated May 9, 2016 4:38:09 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String userId;
     private String password;
     private char userType;
     private String fullName;
     private Patient patient;
     private Doctor doctor;
     private Admin admin;

    public User() {
    }

	
    public User(String userId, String password, char userType, String fullName) {
        this.userId = userId;
        this.password = password;
        this.userType = userType;
        this.fullName = fullName;
    }
    public User(String userId, String password, char userType, String fullName, Patient patient, Doctor doctor, Admin admin) {
       this.userId = userId;
       this.password = password;
       this.userType = userType;
       this.fullName = fullName;
       this.patient = patient;
       this.doctor = doctor;
       this.admin = admin;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public char getUserType() {
        return this.userType;
    }
    
    public void setUserType(char userType) {
        this.userType = userType;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public Doctor getDoctor() {
        return this.doctor;
    }
    
    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }

}


