-- MySQL Script generated by MySQL Workbench
-- 05/09/16 16:10:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `proyecto` ;

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET utf8 ;
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`user` (
  `userId` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `userType` CHAR(1) NOT NULL,
  `fullName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`admin` (
  `userId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`),
  CONSTRAINT `admin_fk1`
    FOREIGN KEY (`userId`)
    REFERENCES `proyecto`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`doctor` (
  `userId` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC),
  CONSTRAINT `doctor_fk1`
    FOREIGN KEY (`userId`)
    REFERENCES `proyecto`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`patient` (
  `userId` VARCHAR(45) NOT NULL,
  `birth` DATE NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC),
  CONSTRAINT `patient_fk1`
    FOREIGN KEY (`userId`)
    REFERENCES `proyecto`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



INSERT INTO `proyecto`.`user` (`userId`, `password`, `userType`, `fullName`) VALUES ('1', 'jorge', 'A', 'Jorge Rodriguez');
INSERT INTO `proyecto`.`user` (`userId`, `password`, `userType`, `fullName`) VALUES ('2', 'andres', 'A', 'Andres Mora');


INSERT INTO `proyecto`.`admin` (`userId`) VALUES ('1');
INSERT INTO `proyecto`.`admin` (`userId`) VALUES ('2');