-- MySQL Script generated by MySQL Workbench
-- 05/23/16 17:33:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `proyecto` ;

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET utf8 ;
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`user` (
  `userId` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `userType` CHAR(1) NOT NULL,
  `fullName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`admin` (
  `userId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`),
  CONSTRAINT `admin_fk1`
    FOREIGN KEY (`userId`)
    REFERENCES `proyecto`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`doctor` (
  `userId` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC),
  CONSTRAINT `doctor_fk1`
    FOREIGN KEY (`userId`)
    REFERENCES `proyecto`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`patient` (
  `userId` VARCHAR(45) NOT NULL,
  `birth` DATE NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC),
  CONSTRAINT `patient_fk1`
    FOREIGN KEY (`userId`)
    REFERENCES `proyecto`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`patientRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`patientRecord` (
  `patientRecordId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`patientRecordId`),
  CONSTRAINT `patientRecord_fk1`
    FOREIGN KEY (`patientRecordId`)
    REFERENCES `proyecto`.`patient` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`patientAppointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`patientAppointments` (
  `patientAppointmentsId` INT NOT NULL,
  `patientRecordId` VARCHAR(45) NOT NULL,
  `doctorId` VARCHAR(45) NOT NULL,
  `date` DATE NULL,
  `time` VARCHAR(15) NULL,
  `description` VARCHAR(100) NULL,
  `results` VARCHAR(100) NULL,
  PRIMARY KEY (`patientAppointmentsId`, `patientRecordId`),
  INDEX `patientAppointments_fk1_idx` (`patientRecordId` ASC),
  INDEX `patientAppointments_fk2_idx` (`doctorId` ASC),
  CONSTRAINT `patientAppointments_fk1`
    FOREIGN KEY (`patientRecordId`)
    REFERENCES `proyecto`.`patientRecord` (`patientRecordId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `patientAppointments_fk2`
    FOREIGN KEY (`doctorId`)
    REFERENCES `proyecto`.`doctor` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `proyecto`.`user` (`userId`, `password`, `userType`, `fullName`) VALUES ('1', 'jorge', 'A', 'Jorge Rodriguez');
INSERT INTO `proyecto`.`user` (`userId`, `password`, `userType`, `fullName`) VALUES ('2', 'andres', 'A', 'Andres Mora');
INSERT INTO `proyecto`.`user` (`userId`, `password`, `userType`, `fullName`) VALUES ('3', 'doctor', 'D', 'Doctor1');
INSERT INTO `proyecto`.`user` (`userId`, `password`, `userType`, `fullName`) VALUES ('4', 'paciente', 'P', 'Paciente1');


INSERT INTO `proyecto`.`admin` (`userId`) VALUES ('1');
INSERT INTO `proyecto`.`admin` (`userId`) VALUES ('2');

INSERT INTO `proyecto`.`doctor` (`userId`, `phone`, `email`) VALUES ('3', '1234-56-78', 'doctor@gmail.com');

INSERT INTO `proyecto`.`patient` (`userId`, `birth`, `address`, `email`, `phone`) VALUES ('4', '1990-03-18', 'paciente', 'paciente@gmail.com', '2345-56-78');